export const FORM_PROJECT = 'FORM_PROJECT';
export const OBTAIN_PROJECTS = 'OBTAIN_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';